server:
  port: 8090
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: mydatabase
      username: dbuser
      password: dbpassword
      authentication-database: mydatabase